
SwatterData = {
	["enabled"] = true,
	["warning"] = true,
	["combat"] = false,
	["errors"] = {
		{
			["message"] = "Interface\\AddOns\\BalancePowerTracker\\Warnings.lua:44: attempt to concatenate a nil value",
			["count"] = 1,
			["addons"] = "  Swatter, v7.0.1 (<%codename%>)\n  Ace3, v\n  AddOnSkins, v3.39\n  Altoholic, vr171\n  AskMrRobot, v45\n  AtlasLoot, vv8.01.04\n  Babylonian, v5.1.DEV.332(/embedded)\n  BalancePowerTracker, v2.0.1\n  Configator, v5.1.DEV.406(/embedded)\n  DataStore, vr59\n  DataStoreCharacters, vr36\n  ElvUI, v10.23\n  Gatherer, v7.0.1\n  SlideBar, v7.0.1 (<%codename%>)\n  BlizRuntimeLib_enUS v7.0.3.70000 <none>\n  (ck=182)\n",
			["locals"] = "me = <table> {\n loadedByDefault = true\n class = <table> {\n }\n}\ngetEnv = nil\nreset = nil\nUIFrameFlash = <function> defined @Interface\\FrameXML\\UIParent.lua:3313\nPlaySoundFile = <function> defined =[C]:-1\nSpellActivationOverlay_OnEvent = <function> defined @Interface\\FrameXML\\SpellActivationOverlay.lua:15\nSpellActivationOverlayFrame = SpellActivationOverlayFrame {\n overlaysInUse = <table> {\n }\n unusedOverlays = <table> {\n }\n 0 = <userdata>\n}\nabs = <function> defined =[C]:-1\ngetEclipseKey = <table> {\n -100 = <table> {\n }\n 100 = <table> {\n }\n}\n(*temporary) = <table> {\n RealLunarEclipse = <table> {\n }\n}\n(*temporary) = <table> {\n playThis = false\n MSBTThis = true\n color = <table> {\n }\n flashThis = false\n warnThis = true\n sound = \"Interface\\Quiet.ogg\"\n}\n(*temporary) = nil\n(*temporary) = \" soon!\"\n(*temporary) = <function> defined =[C]:-1\n(*temporary) = 171743\n(*temporary) = nil\n(*temporary) = \"attempt to concatenate a nil value\"\n",
			["timestamp"] = "2016-10-14 18:29:35",
			["context"] = "Global",
			["stack"] = "Interface\\AddOns\\BalancePowerTracker\\Warnings.lua:44: in main chunk\n",
		}, -- [1]
		{
			["message"] = "Interface\\AddOns\\renewing-mist-tracker\\Main.lua:367: attempt to call global 'GetGlyphSocketInfo' (a nil value)",
			["count"] = 1,
			["addons"] = "  Swatter, v7.0.1 (<%codename%>)\n  Ace3, v\n  AddOnSkins, v3.39\n  Altoholic, vr171\n  AskMrRobot, v45\n  AtlasLoot, vv8.01.04\n  Babylonian, v5.1.DEV.332(/embedded)\n  BalancePowerTracker, v2.0.1\n  BlockChinese, v1.3\n  BulkOrder, vv1.18\n  Configator, v5.1.DEV.406(/embedded)\n  CrossRealmAssist, v0.8 beta\n  DataStore, vr59\n  DataStoreAchievements, vr42\n  DataStoreAgenda, vr23\n  DataStoreAuctions, v6.0.001\n  DataStoreCharacters, vr36\n  DataStoreContainers, vr53\n  DataStoreCrafts, vr73\n  DataStoreCurrencies, vr31\n  DataStoreGarrisons, vr16\n  DataStoreInventory, vr46\n  DataStoreMails, vr46\n  DataStorePets, vr39\n  DataStoreQuests, vr36\n  DataStoreReputations, vr37\n  DataStoreSpells, vr27\n  DataStoreStats, vr26\n  DataStoreTalents, vr54\n  DBMCore, v\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  ElvUI, v10.23\n  ElvUIEverySecondCounts, v1.17\n  epgplootmaster, v6.71\n  epgplootmasterml, v6.71\n  ExRT, v3780\n  Gatherer, v7.0.1\n  GTFO, v4.40.3\n  MasterPlanA, vA\n  MikScrollingBattleText, v5.7.146\n  MogIt, v3.6.5\n  NiceDamage, v40000\n  ogear, v0.1.8\n  oqueue, v2.1.1\n  otradechat, v0.0.6\n  Overachiever, v0.96\n  Pawn, v2.1\n  Raven, vr375\n  RCLootCouncil, v2.1.5\n  renewingmisttracker, vr20160103060745\n  Routes, vv1.5.4\n  rTimeToDie, v\n  Simulationcraft, v1.5.1\n  Skada, v1.5-11\n  SlideBar, v7.0.1 (<%codename%>)\n  SmartTabTarget, v\n  SorhaQuestLog, vv1.5.0.1\n  SpellFlash, v6.24.1\n  SpellFlashCore, v2.1.1\n  StaggerMeter, v\n  StrataFix, v3.5.1\n  TellMeWhen, v8.1.2\n  ThogarAssist, v\n  TradeSkillMaster, vv3.6.8\n  TradeSkillMasterAccounting, vv3.0.16\n  TradeSkillMasterAdditions, vv2.2\n  TradeSkillMasterAppHelper, vv3.0.1\n  TradeSkillMasterAuctionDB, vv3.1.13\n  TradeSkillMasterAuctioning, vv3.0.13\n  TradeSkillMasterCrafting, vv3.1.16\n  TradeSkillMasterDestroying, vv3.1.4\n  TradeSkillMasterItemTracker, vv2.2\n  TradeSkillMasterMailing, vv3.0.12\n  TradeSkillMasterShopping, vv3.4.1\n  TradeSkillMasterWarehousing, vv3.0.3\n  TradeSkillMasterWoWuction, vv3.1\n  VelhariHealthFix, v\n  WeakAuras, v2.2.1.6\n  BlizRuntimeLib_enUS v7.0.3.70000 <none>\n  (ck=7f6)\n",
			["locals"] = "",
			["timestamp"] = "2016-10-14 18:29:59",
			["context"] = "Global",
			["stack"] = "[C]: in function `GetGlyphSocketInfo'\nInterface\\AddOns\\renewing-mist-tracker\\Main.lua:367: in function `QueryGlyphs'\nInterface\\AddOns\\renewing-mist-tracker\\Main.lua:565: in function <Interface\\AddOns\\renewing-mist-tracker\\Main.lua:530>\n",
		}, -- [2]
		{
			["message"] = "...nterface\\AddOns\\BalancePowerTracker\\ModuleLoader.lua:154: attempt to call field 'LoadModule' (a nil value)",
			["count"] = 1,
			["addons"] = "  Swatter, v7.0.1 (<%codename%>)\n  Ace3, v\n  AddOnSkins, v3.39\n  Altoholic, vr171\n  AskMrRobot, v45\n  AtlasLoot, vv8.01.04\n  Babylonian, v5.1.DEV.332(/embedded)\n  BalancePowerTracker, v2.0.1\n  BlockChinese, v1.3\n  BulkOrder, vv1.18\n  Configator, v5.1.DEV.406(/embedded)\n  CrossRealmAssist, v0.8 beta\n  DataStore, vr59\n  DataStoreAchievements, vr42\n  DataStoreAgenda, vr23\n  DataStoreAuctions, v6.0.001\n  DataStoreCharacters, vr36\n  DataStoreContainers, vr53\n  DataStoreCrafts, vr73\n  DataStoreCurrencies, vr31\n  DataStoreGarrisons, vr16\n  DataStoreInventory, vr46\n  DataStoreMails, vr46\n  DataStorePets, vr39\n  DataStoreQuests, vr36\n  DataStoreReputations, vr37\n  DataStoreSpells, vr27\n  DataStoreStats, vr26\n  DataStoreTalents, vr54\n  DBMCore, v\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  ElvUI, v10.23\n  ElvUIEverySecondCounts, v1.17\n  epgplootmaster, v6.71\n  epgplootmasterml, v6.71\n  ExRT, v3780\n  Gatherer, v7.0.1\n  GTFO, v4.40.3\n  MasterPlanA, vA\n  MikScrollingBattleText, v5.7.146\n  MogIt, v3.6.5\n  NiceDamage, v40000\n  ogear, v0.1.8\n  oqueue, v2.1.1\n  otradechat, v0.0.6\n  Overachiever, v0.96\n  Pawn, v2.1\n  Raven, vr375\n  RCLootCouncil, v2.1.5\n  renewingmisttracker, vr20160103060745\n  Routes, vv1.5.4\n  rTimeToDie, v\n  Simulationcraft, v1.5.1\n  Skada, v1.5-11\n  SlideBar, v7.0.1 (<%codename%>)\n  SmartTabTarget, v\n  SorhaQuestLog, vv1.5.0.1\n  SpellFlash, v6.24.1\n  SpellFlashCore, v2.1.1\n  StaggerMeter, v\n  StrataFix, v3.5.1\n  TellMeWhen, v8.1.2\n  TellMeWhenOptions, v\n  ThogarAssist, v\n  TradeSkillMaster, vv3.6.8\n  TradeSkillMasterAccounting, vv3.0.16\n  TradeSkillMasterAdditions, vv2.2\n  TradeSkillMasterAppHelper, vv3.0.1\n  TradeSkillMasterAuctionDB, vv3.1.13\n  TradeSkillMasterAuctioning, vv3.0.13\n  TradeSkillMasterCrafting, vv3.1.16\n  TradeSkillMasterDestroying, vv3.1.4\n  TradeSkillMasterItemTracker, vv2.2\n  TradeSkillMasterMailing, vv3.0.12\n  TradeSkillMasterShopping, vv3.4.1\n  TradeSkillMasterWarehousing, vv3.0.3\n  TradeSkillMasterWoWuction, vv3.1\n  VelhariHealthFix, v\n  WeakAuras, v2.2.1.6\n  BlizRuntimeLib_enUS v7.0.3.70000 <none>\n  (ck=80d)\n",
			["locals"] = "",
			["timestamp"] = "2016-10-14 18:30:07",
			["context"] = "Global",
			["stack"] = "[C]: in function `LoadModule'\n...nterface\\AddOns\\BalancePowerTracker\\ModuleLoader.lua:154: in function `CheckAll'\n...nterface\\AddOns\\BalancePowerTracker\\ModuleLoader.lua:92: in function <...nterface\\AddOns\\BalancePowerTracker\\ModuleLoader.lua:86>\n",
		}, -- [3]
		{
			["message"] = "Interface\\AddOns\\SpellFlash\\SpellFlash.lua:1013: attempt to compare number with string",
			["count"] = 2,
			["addons"] = "  Swatter, v7.0.1 (<%codename%>)\n  Ace3, v\n  AddOnSkins, v3.39\n  Altoholic, vr171\n  AskMrRobot, v45\n  AtlasLoot, vv8.01.04\n  Babylonian, v5.1.DEV.332(/embedded)\n  BalancePowerTracker, v2.0.1\n  BlockChinese, v1.3\n  BulkOrder, vv1.18\n  Configator, v5.1.DEV.406(/embedded)\n  CrossRealmAssist, v0.8 beta\n  DataStore, vr59\n  DataStoreAchievements, vr42\n  DataStoreAgenda, vr23\n  DataStoreAuctions, v6.0.001\n  DataStoreCharacters, vr36\n  DataStoreContainers, vr53\n  DataStoreCrafts, vr73\n  DataStoreCurrencies, vr31\n  DataStoreGarrisons, vr16\n  DataStoreInventory, vr46\n  DataStoreMails, vr46\n  DataStorePets, vr39\n  DataStoreQuests, vr36\n  DataStoreReputations, vr37\n  DataStoreSpells, vr27\n  DataStoreStats, vr26\n  DataStoreTalents, vr54\n  DBMCore, v\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  ElvUI, v10.23\n  ElvUIConfig, v1.04\n  ElvUIEverySecondCounts, v1.17\n  epgplootmaster, v6.71\n  epgplootmasterml, v6.71\n  ExRT, v3780\n  Gatherer, v7.0.1\n  GTFO, v4.40.3\n  MasterPlanA, vA\n  MikScrollingBattleText, v5.7.146\n  MogIt, v3.6.5\n  NiceDamage, v40000\n  ogear, v0.1.8\n  oqueue, v2.1.1\n  otradechat, v0.0.6\n  Overachiever, v0.96\n  OverachieverTabs, v0.96\n  Pawn, v2.1\n  Raven, vr375\n  RCLootCouncil, v2.1.5\n  renewingmisttracker, vr20160103060745\n  Routes, vv1.5.4\n  rTimeToDie, v\n  Simulationcraft, v1.5.1\n  Skada, v1.5-11\n  SlideBar, v7.0.1 (<%codename%>)\n  SmartTabTarget, v\n  SorhaQuestLog, vv1.5.0.1\n  SpellFlash, v6.24.1\n  SpellFlashCore, v2.1.1\n  StaggerMeter, v\n  StrataFix, v3.5.1\n  TellMeWhen, v8.1.2\n  TellMeWhenOptions, v\n  ThogarAssist, v\n  TradeSkillMaster, vv3.6.8\n  TradeSkillMasterAccounting, vv3.0.16\n  TradeSkillMasterAdditions, vv2.2\n  TradeSkillMasterAppHelper, vv3.0.1\n  TradeSkillMasterAuctionDB, vv3.1.13\n  TradeSkillMasterAuctioning, vv3.0.13\n  TradeSkillMasterCrafting, vv3.1.16\n  TradeSkillMasterDestroying, vv3.1.4\n  TradeSkillMasterItemTracker, vv2.2\n  TradeSkillMasterMailing, vv3.0.12\n  TradeSkillMasterShopping, vv3.4.1\n  TradeSkillMasterWarehousing, vv3.0.3\n  TradeSkillMasterWoWuction, vv3.1\n  VelhariHealthFix, v\n  WeakAuras, v2.2.1.6\n  BlizRuntimeLib_enUS v7.0.3.70000 <none>\n  (ck=83c)\n",
			["locals"] = "",
			["timestamp"] = "2016-10-14 18:41:07",
			["context"] = "Global",
			["stack"] = "[C]: ?\nInterface\\AddOns\\SpellFlash\\SpellFlash.lua:1013: in function `?'\nInterface\\AddOns\\SpellFlash\\SpellFlash.lua:842: in function <Interface\\AddOns\\SpellFlash\\SpellFlash.lua:841>\n",
		}, -- [4]
		{
			["message"] = "SendChatMessage(): Chat message must be UTF-8 text",
			["count"] = 3,
			["addons"] = "  Swatter, v7.0.1 (<%codename%>)\n  Ace3, v\n  AddOnSkins, v3.39\n  Altoholic, vr171\n  AskMrRobot, v45\n  AtlasLoot, vv8.01.04\n  Babylonian, v5.1.DEV.332(/embedded)\n  BalancePowerTracker, v2.0.1\n  BlockChinese, v1.3\n  BulkOrder, vv1.18\n  Configator, v5.1.DEV.406(/embedded)\n  CrossRealmAssist, v0.8 beta\n  DataStore, vr59\n  DataStoreAchievements, vr42\n  DataStoreAgenda, vr23\n  DataStoreAuctions, v6.0.001\n  DataStoreCharacters, vr36\n  DataStoreContainers, vr53\n  DataStoreCrafts, vr73\n  DataStoreCurrencies, vr31\n  DataStoreGarrisons, vr16\n  DataStoreInventory, vr46\n  DataStoreMails, vr46\n  DataStorePets, vr39\n  DataStoreQuests, vr36\n  DataStoreReputations, vr37\n  DataStoreSpells, vr27\n  DataStoreStats, vr26\n  DataStoreTalents, vr54\n  DBMCore, v\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  ElvUI, v10.23\n  ElvUIConfig, v1.04\n  ElvUIEverySecondCounts, v1.17\n  epgplootmaster, v6.71\n  epgplootmasterml, v6.71\n  ExRT, v3780\n  Gatherer, v7.0.1\n  GTFO, v4.40.3\n  MasterPlanA, vA\n  MikScrollingBattleText, v5.7.146\n  MogIt, v3.6.5\n  NiceDamage, v40000\n  ogear, v0.1.8\n  oqueue, v2.1.1\n  otradechat, v0.0.6\n  Overachiever, v0.96\n  OverachieverTabs, v0.96\n  Pawn, v2.1\n  Raven, vr375\n  RCLootCouncil, v2.1.5\n  renewingmisttracker, vr20160103060745\n  Routes, vv1.5.4\n  rTimeToDie, v\n  Simulationcraft, v1.5.1\n  Skada, v1.5-11\n  SlideBar, v7.0.1 (<%codename%>)\n  SmartTabTarget, v\n  SorhaQuestLog, vv1.5.0.1\n  SpellFlash, v6.24.1\n  SpellFlashCore, v2.1.1\n  StaggerMeter, v\n  StrataFix, v3.5.1\n  TellMeWhen, v8.1.2\n  TellMeWhenOptions, v\n  ThogarAssist, v\n  TradeSkillMaster, vv3.6.8\n  TradeSkillMasterAccounting, vv3.0.16\n  TradeSkillMasterAdditions, vv2.2\n  TradeSkillMasterAppHelper, vv3.0.1\n  TradeSkillMasterAuctionDB, vv3.1.13\n  TradeSkillMasterAuctioning, vv3.0.13\n  TradeSkillMasterCrafting, vv3.1.16\n  TradeSkillMasterDestroying, vv3.1.4\n  TradeSkillMasterItemTracker, vv2.2\n  TradeSkillMasterMailing, vv3.0.12\n  TradeSkillMasterShopping, vv3.4.1\n  TradeSkillMasterWarehousing, vv3.0.3\n  TradeSkillMasterWoWuction, vv3.1\n  VelhariHealthFix, v\n  WeakAuras, v2.2.1.6\n  BlizRuntimeLib_enUS v7.0.3.70000 <none>\n  (ck=83c)\n",
			["locals"] = "",
			["timestamp"] = "2016-10-14 18:46:54",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: ?\n[C]: in function `SendChatMessage'\nInterface\\AddOns\\otradechat\\otradechat.lua:174: in function `channel_say'\nInterface\\AddOns\\otradechat\\otradechat.lua:301: in function `filterFunc'\nInterface\\AddOns\\ElvUI\\Modules\\chat\\chat.lua:1041: in function `ChatFrame_MessageEventHandler'\nInterface\\AddOns\\ElvUI\\Modules\\chat\\chat.lua:1450: in function `ChatFrame_OnEvent'\nInterface\\AddOns\\ElvUI\\Modules\\chat\\chat.lua:1456: in function <Interface\\AddOns\\ElvUI\\Modules\\chat\\chat.lua:1455>\n",
		}, -- [5]
	},
	["autoshow"] = true,
}
